### ISSUE TITLE
openssl doesn't like docs.ava.network's tls certs "unable to get local issuer certificate"

### ISSUE THREAD

**Issue by bhyde** [ava-labs/gecko#159]
Openssl complains about the tls certs of docs.ava.network

I wanted to capture some of the doc, and did this:
```
bash-3.2$ echo 'y' | w3m -dump https://docs.ava.network/v1.0/en/api/keystore/ > /tmp/keystore.txt
Accept unsecure SSL session: unverified: unable to get local issuer certificate
```
The `echo 'y'` was necessary to force w3m to proceed.

Openssl will show the certificate chain and do some validation.  It complains:
```
bash-3.2$ echo '' | openssl s_client -connect docs.ava.network:443 -showcerts 2>&1 | grep verify
verify error:num=20:unable to get local issuer certificate
verify return:1
verify error:num=21:unable to verify the first certificate
verify return:1
    Verify return code: 21 (unable to verify the first certificate)
```

FYI `verify return:1` is actually the good result, but the `verify error:..` aren't?

I can show you a bit more context, but it doesn't help me...
```
bash-3.2$ echo '' | openssl s_client -connect docs.ava.network:443 -showcerts 2>&1 | grep -C 3 verify
depth=0 CN = docs.ava.network
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = docs.ava.network
--
depth=0 CN = docs.ava.network
verify error:num=21:unable to verify the first certificate
verify return:1
CONNECTED(0000000B)
---
Certificate chain
--
--

    Start Time: 1589297622
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)
---
DONE
bash-3.2$
```

**Comment by danlaine** [comment]
@collincusce Hey, can you look into this please?

**Comment by collincusce** [comment]
Hey so I ran this through a few checkers, @bhyde and none of them saw the problem. I did a renew of the cert and it fixed it despite the previous cert not being expired. I am completely unsure why this happened. 

Keep in mind, I'm a jack-of-all-master-of-none so if you have tips why this went this way, I'm down to listen.

Browsers, Chrome (Mobile and Desktop), Firefox (Desktop): Both reported cert was a-ok.

This site reported cert was a-ok: https://check-your-website.server-daten.de/?q=docs.ava.network

Aside from the B-grade due to TLS 1.0 and 1.1 support (which I'm going to disable shortly), this site said a-ok: https://www.ssllabs.com/ssltest/analyze.html?d=docs.ava.network

OpenSSL was not happy and I saw the same thing you did.

I renewed the cert and then suddenly OpenSSL was happy again. I really don't know what happened to fix it, though, which is not great, but sometimes that happens and we can only monitor it to see if it happens again and figure out what's different.

@bhyde can you verify that your openssl is reporting properly?

**Comment by collincusce** [comment]
![Screenshot from 2020-05-12 13-15-55](https://user-images.githubusercontent.com/6778681/81724666-c0237600-9452-11ea-85ca-1e034d4665f5.png)

**Comment by JuergenAuer** [comment]
> I am completely unsure why this happened.

The last check - https://check-your-website.server-daten.de/?q=docs.ava.network#connections - has a correct chain. See the connections - part.

> 1 | CN=docs.ava.network
> -- | --
>  |   | 2 | CN=Let's Encrypt Authority X3, O=Let's Encrypt, C=US

The older check sends only the leaf certificate:

> Chain - incomplete |   | 1 | CN=docs.ava.network

So the intermediate certificate from Letsencrypt is missing -> that's the typical OpenSsl error message:

> verify error:num=21:unable to verify the first certificate

So the intermediate certificate wasn't installed. Recreating the certificate installed it.

Conclusion: Use always fullchain.pem, not cert.pem. fullchain.pem contains both certificates.

PS: Followed the link in the protocol of "check-your-website".

**Comment by collincusce** [comment]
BOOM! And we have an answer. FYI, I had the same issue on files.avalabs.org so this knocked out both of the problems. Thanks for the report, I'm going to call this one complete.

**Comment by bhyde** [comment]
Thank you.  OpenSSL, w3m, and @bhyde are all happy now!
