### ISSUE TITLE
The staking port number should be increment after every crash

### ISSUE THREAD

**Issue by AlexDCryptoC** [ava-labs/gecko#182]
I just set up my node few minutes ago and after the last upgrade to the latest github version, i had again to increment my staking port number with 1 before starting the node. I'm at 9655 now :D 

./build/ava --staking-port=9655

**Comment by StephenButtolph** [comment]
Thanks for bringing this up. I think this is a side effect of #109. The plugins seem to have a reference to the main networking file descriptor. Because the plugins aren't terminated normally during a crash, the file descriptor isn't cleaned up by the OS. Which means the port looks busy even after exiting the program.

Try checking to see if there are some stale `evm` processes running on your system. I think that's the root cause of the error.

**Comment by danlaine** [comment]
@AlexDCryptoC Have you had this issue since the Denali release?

**Comment by AlexDCryptoC** [comment]
I'm very disappointed and i had no time to join Denali. I just submitted in this morning but the slots are full and seems there is no enough space for me anymore :(

**Comment by danlaine** [comment]
@AlexDCryptoC You can still run a node even if you're not participating in the challenges :) 
I haven't seen this issue reported in a few weeks so I'm gonna close.
Let us know if you see it again. Cheers.

**Comment by AlexDCryptoC** [comment]
sure, cheers!
