### ISSUE TITLE
My balance appears at the wrong X-chain address after my fixed-cap asset transfers

### ISSUE THREAD

**Issue by sonersulun** [ava-labs/gecko#255]
**_Describe the bug_**

My balance appears at the wrong X chain address after my fixed-cap asset transfers.

**_To Reproduce_**

I have created  a fixed-cap asset a amount of 1000 named sugar with my X-Chain adress : X-91sDF412f3rm3qJkHBv1Mzp7dKLZQVujH

Next step; i sent 1 sugar asset two times to X-Chain adress:  X-ENwFeaNSbKXF8S6pQmFPVhYm4HWR7wRuy

I saw zero when i checked my balance for my X-chain adress:   X-91sDF412f3rm3qJkHBv1Mzp7dKLZQVujH

On the other hand, 
I saw my balance 998 when i checked my balance other X-Chain address: X-3bajmo5cCpRpxeU6ARKUPJ3GCRNsd6s3K

**Expected behavior**

I should have seen my balance 998 on my X-Chain adress:X-91sDF412f3rm3qJkHBv1Mzp7dKLZQVujH

**Screenshots**

![sugar-createFixedCap](https://user-images.githubusercontent.com/67014179/85465353-5f3ea000-b5b1-11ea-9f75-d77fdbed64ce.PNG)
![sugar balance on created X-Chain adress](https://user-images.githubusercontent.com/67014179/85465446-7aa9ab00-b5b1-11ea-80ca-2b6a7bf02488.PNG)
![send sugar amount 1_LI PNG](https://user-images.githubusercontent.com/67014179/85465514-8eeda800-b5b1-11ea-81e2-b56168905888.jpg)
![send  again sugar amount 1_LI PNG](https://user-images.githubusercontent.com/67014179/85465536-94e38900-b5b1-11ea-88be-7762e2d28bce.jpg)
![check balance on created x-chain adress](https://user-images.githubusercontent.com/67014179/85465598-a3ca3b80-b5b1-11ea-9a41-ffebcf4dc463.PNG)
![check balance on my other X-Chain adress](https://user-images.githubusercontent.com/67014179/85465626-acbb0d00-b5b1-11ea-96b4-a7278fb3f6db.PNG)

**Operating System**
Ubuntu == 18.04

**Comment by aaronbuchwald** [comment]
Thanks for bringing this up @sonersulun.

This actually looks like perfectly normal behavior due to how the Send API call works. 

Do the funds show up in the address X-ENwFeaNSb... and it's just that they are no longer in the original address that the asset was created with?

As long as the sent funds are showing up there, then this is perfectly normal. The Send call looks through all of the utxos matching the asset id you're trying to spend that are owned by your x chain addresses. If these utxos have more total funds than you are actually trying to send, then it will send the excess funds to a change address that's controlled by your account. That's why the 998 balance is showing up on your other account address.

Would it be helpful for you if there were another parameter that you could set that would designate the change address?

**Comment by danlaine** [comment]
Closing this for age. @sonersulun Let us know if you have any issues with a newer release
