### ISSUE TITLE
admin API broken in 0.5.7 ?

### ISSUE THREAD

**Issue by ekherit** [ava-labs/gecko#259]
**Describe the bug**
Any admin API was broken after upgrade to 0.5.7

**To Reproduce**
1. Upgrade and build to new version from scratch: 
go get -v -d github.com/ava-labs/gecko/...

2. Run 
./build/ava --public-ip=127.0.0.1

3.  Do query
curl -X POST --data '{
    "jsonrpc": "2.0",
   "method": "admin.getNodeID",
    "params":{},
    "id": 1
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/admin
Answer:
404 page not found

**Expected behavior**
Json structure with result

**Operating System**
Debian testing

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by tbrunain** [comment]
it's most likely because the `admin` api is now disabled by default .

If you want to have it enable , you must run gecko with ` --api-admin-enabled=true` .

Maybe before doing so check the new `Info` api : https://docs.ava.network/v1.0/en/api/info/ 

Some endpoints that were present in /admin have been moved there . (peers, nodeId, networkId, ...)

**Comment by aaronbuchwald** [comment]
Thanks @tbrunain , that's correct. The API calls that have been moved to Info are still in admin (which is now disabled by default), but deprecated. They will be removed from the Admin API completely in the future and will then only be in the Info API. So I would recommend switching to using the Info API whenever possible.
